#!/usr/bin/env bash
export HADOOP_VERSION=3.3.0
export DERBY_VERSION=10.10.2.0
export HIVE_VERSION=3.1.2
export OLK_VERSION=1.3.0

export USER_NAME=${USER}
export USER_ID=$(id -u "${USER_NAME}")
export GROUP_ID=$(id -g "${USER_NAME}")

#Whether to run all services inside a single container.
#If enabled, cannot scale datanodes to multiple instances if required.
export EMBED_IN_SINGLE_CONTAINER=true

#Whether OLK should be enabled.
export OLK_ENABLED=true

##### DONT CHANGE BELOW THIS #######
export OLK_DEPENDENCY="hive"

if [ "${EMBED_IN_SINGLE_CONTAINER}" == "true" ]; then
   export OLK_DEPENDENCY="hive-hadoop"
fi
